version: '3'

services:
  react_app:
    build: ./react_app
    ports:
      - '3000:3000'
    volumes:
      - ./react_app:/react_app

  go_api:
    build: ./gin_todo
    volumes:
      - ./gin_todo/:/go/src/gin_todo
    ports:
      - "8083:8083"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./db_data:/var/lib/mysql
